== Single Sign-On (SSO)

The Auth SDK uses OpenID Connect http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[Auhtorization Code Flow] to achieve SSO via a mobile device browser.

'''

=== Prerequisite's
. A running AeroGear auth service (Keycloak)
. Two Android app's that have imported and initialised the Auth SDK module - link:auth.adoc[AeroGear Services Auth SDK].

'''

=== Steps to achieve SSO via a device browser
For this guide, let's assume that your two Android apps are called **Email App** and **Messaging App**.

==== Setup Keycloak

include::keycloak.adoc[]

==== Configuration File in the Mobile Apps
From following the link:auth.adoc[AeroGear Services Auth SDK] setup, there should be a configuration file, `mobile-services.json`, inside the assets directory of your Android project.  It's important that the Keycloak configuration defined in this file matches the Keycloak client that the app intends to use. +
So for the *Email App* `mobile-services.json` file, ensure that the configuration defined in this file matches the configuration specified in the *Keycloak Email Client*.  The same applies for the *Messaging App*

'''
Now that your two Android apps and Keycloak clients are setup, sign into the *Email App* with the user you have previously created. You should be redirected to your device browser which should have loaded the Keycloak login page.  Next, enter in your credentials and login.  You'll be asked to enter a new password for the user. You have now been authenticated on the *Email App* via your device browser.  Finally, try sign into the *Messaging App* with the same user credentials, you should be automatically logged in as you have been previously authenticated in the *Email App* via the *_same_* device browser.
