package org.aerogear.mobile.auth.configuration;

public enum BrowserType {
    CHROME, CHROME_DEFAULT, CHROME_DEFAULT_CUSTOM_TAB, FIREFOX, FIREFOX_DEFAULT, SAMSUNG_BROWSER, SAMSUNG_BROWSER_DEFAULT, SAMSUNG_BROWSER_DEFAULT_CUSTOM_TAB
}
