== Getting Started with AeroGear SDK for Android

Following guide provides general information for starting with AeroGear Services SDK.

== Prerequisites

You will need the following installed on your system  

 * Android SDK or Android Studio from https://developer.android.com/studio/index.html[Google]

It is recommended you have the following installed

 * The latest version of http://openjdk.java.net/install/index.html[OpenJDK]

== Using a Published SDK

=== jcenter()

To use a published version of the SDK you have to add jcenter to the build.grade file in your project's root directory

[source, groovy]
----
allprojects {
    repositories {
        jcenter() // <-- Add This line
        google()
    }
}
----

=== Reference the Dependencies

In the build.gradle file of your app you can begin adding dependencies provided by the SDK.

----
dependencies {
    ...
    implementation 'org.aerogear:android-push:[version]'
    implementation 'org.aerogear:android-auth:[version]'
    implementation 'org.aerogear:android-security:[version]'


}
----

A full list of releases can be viewed https://github.com/aerogear/aerogear-android-sdk/releases[here]

== Installing Local Build of SDK

Alternatively the SDK can be installed manually instead of using a published version.

=== Clone and build the library

[source, sh]
----
git clone https://github.com/aerogear/aerogear-android-sdk
cd aerogear-android-sdk
./gradlew install
----

You can verify the install went well by checking your local maven repository

----
ls ~/.m2/repository/org/aerogear

# Should output auth core
----

=== MavenLocal()

If you are using a build of the SDK from source you will need to add mavenLocal() to the build.gradle file in your project's root directory.

[source, groovy]
----
allprojects {
    repositories {
        mavenLocal() // <-- Add This line
        google()
        jcenter()
    }
}
----

=== Reference the Dependencies

In the build.gradle file of your app you can begin adding dependencies provided by the SDK.

----
dependencies {
    ...
    implementation 'org.aerogear:android-push:[version]-SNAPSHOT'
    implementation 'org.aerogear:android-auth:[version]-SNAPSHOT'
    implementation 'org.aerogear:android-security:[version]-SNAPSHOT'
}
----

== Using the SDK

Please follow individual SDK's documentation to see how to add them to the project

 * link:./metrics.adoc[Metrics] 
 * link:./auth.adoc[Auth]
 * link:./push.adoc[Push]

== Certificate Pinning

To implement certificate pinning in the individual SDKs, see link:./certificate-pinning.adoc[the certificate pinning guide].
