== Single Sign-On (SSO) via the Device Browser

The Auth SDK uses OpenID Connect  http://openid.net/specs/openid-connect-core-1_0.html#CodeFlowAuth[Auhtorization Code Flow] to achieve SSO via a mobile device browser.

'''

=== Prerequisite's
. Add the Android SDK to your app - link:../getting-started.adoc[Getting Started with AeroGear Services Android SDK].
. Import the Core SDK module - link:../core/README.adoc[AeroGear Services Core SDK].
. Import the Auth SDK module - link:/README.adoc[AeroGear Services Auth SDK]. 
. Setup a Keycloak instance:
* *Setup Keycloak in an Openshift Cluster (Recommended):*
** If you do not have mobile services enabled in your openshift cluster please follow this link:https://github.com/aerogear/mobile-core/blob/master/docs/walkthroughs/local-setup.adoc[Local Setup] guide.
** Navigate to your Openshift cluster and in the Service Catalog search for the Keycloak service.
** Click on the Keycloak service and you will be prompted to fill in details about your app.  For now you can leave these as they are.  Navigate through the setup and click Create.  This will provision the Keycloak service in the project you specified.
** After provisioning, the Keycloak service will be available at the exposed Route. You can view this route inside your project or use the below command to get the route: 
----
oc get route keycloak --template "http://{{.spec.host}} "
----
The route should look like `https://keycloak-myproject.192.168.37.1.nip.io/auth/`. +

* *To setup standalone Keycloak follow Keycloak's guide link:/https://github.com/keycloak/keycloak/blob/master/README.md[here].*

'''

=== Steps to achieve SSO via device browser
For this guide, let's assume that you have two apps, **Email App** and **Messaging App**.

==== Setup Keycloak Email Client
. Once you have a keycloak instance running, navigate to the Keycloak Console. This can be done by navigating to the exposed route (described in step 4 of the <<Prerequisite’s>>) and clicking on *Administration Console*.
. Sign in using the username and password specified when creating Keycloak.
. Add a new *Realm* if one has not yet been created (if you've setup Keycloak in Openshift the realm will be `myproject`).
. Inside the *Realm*, create a new OIDC client by clicking on the *Clients* tab in the left menu. 
. On clicking *Create*, you will be brought to the *Add Client* page.  The *Client ID* is the client identifier for OIDC requests. This should be a simple alpha-numeric string e.g. the name of your app - `emailapp`.  Next select *openid-connect* in the *Client Protocol* drop down box. The *Client Template* and *Root URL* can be ignored for this setup. Finally click *Save* and now a client for the *Email App* has been created.
. On creating the client, you will be brought to the *Client Settings* page.  The important configuration on this page is the *Valid Redirect URI*.  This value (schema) should be the same as the schema that has been specified in the *Email App Android Project* (more on this later). Also ensure that *Enabled* and *Standard Flow Enabled* are set to *On*. The *Client Protocol* must be *openid-connect* and ensure that you enter a valid base url for the *Web Origin* configuration. For more information on the  configuration items in the client settings see link:/http://www.keycloak.org/docs/latest/server_admin/index.html#oidc-clients[Keycloak OIDC Clients].
. Finally, create a user inside the Realm by navigating to *Users* on the left hand side.  Click add user and fill in the user details.  On clicking save, ensure to navigate to the *Credentials* tab of the new user and give them a password.  You'll be prompted to change this password on first login.

==== Setup Keycloak Messaging Client
. Follow steps 4-7 of <<Setup Keycloak Email Client>>.

==== Setup Email App
. It's important that the redirct uri in the Email App is also one of the *Valid Redirect URIs* specified in the *Keycloak Email Client*.  This ensures that the device browser used to perform the login knows to return to the *Email App* after performing authentication.  The redirect uri for the Email App can be specified in `android.defaultConfig.manifestPlaceholders` in the `build.gradle` file of the app.  It's best practice to use the package identifier of the app as the schema of the redirect uri to avoid conflicts e.g.
```
manifestPlaceholders = ['appAuthRedirectScheme': 'org.aerogear.mobile.emailapp']
```
Where `org.aerogear.mobile.emailapp` is your package identifier. +

. Now you need to instruct the Auth SDK in the Email App to use this redirect uri. To do this the Auth SDK needs to be initialised.  A quick guide on how to initialise the Auth SDK can be found here - link:/toAidensDocs.adoc[Initializing the SDK].  +
[NOTE]
this is the redirect uri that needs to be added to the *Keycloak Email Client* i.e. one of the *Valid Redirect URIs* should be `org.aerogear.mobile.emailapp:/callback`. +


. Lastly, your app needs a `mobile-service.json` configuration file. In this file you can specifiy different services your app uses like Keycloak.  So the information entered previously for <<Setup Keycloak Email Client>> will need to be specified in this JSON file.  The configuration should have the following configuration items:
```
{
    "version": 1,
    "clusterName": "https://192.168.37.1:8443",
    "namespace": "myproject",
    "services": [
        {
            "id": "keycloak",
            "name": "keycloak",
            "type": "keycloak",
            "url": "https://keycloak-myproject.192.168.37.1.nip.io",
            "config": {}
        }
    ]
}
```
*`clusterName`*: This is the URL to your Openshift cluster. +
*`namespace`*: This is the project in Openshift where you can access resources e.g. the two Android app's you have created. +
*`services`*: These are the services your app uses.  For this setup we are only using Keycloak. +
*`id`*: The ID of the service. +
*`name`*: The name of the service. +
*`type`*: The type of the service. +
*`url`*: This is your Keycloak server base url. +
*`config`*: The configuration for the service specified. This configuration is for the Email App so it can be got by navigating to the Clients section in Keycloak, clicking clients and navigating to the *Installation* tab.  In this tab you can select *Keycloak OIDC JSON* from the *Format Option* dropdown and copy and paste that configuration into the config object here. +
So after adding in that Keycloak Email Client configuration, the `mobile-service.json` file will look like: 

```
{
    "version": 1,
    "clusterName": "https://192.168.37.1:8443",
    "namespace": "myproject",
    "services": [
        {
            "id": "keycloak",
            "name": "keycloak",
            "type": "keycloak",
            "url": "https://keycloak-myproject.192.168.37.1.nip.io",
            "config": {
                  "realm": "myproject",
                  "auth-server-url": "https://keycloak-myproject.192.168.37.1.nip.io/auth",
                  "ssl-required": "external",
                  "resource": "emailapp",
                  "public-client": true,
                  "use-resource-role-mappings": true,
                  "confidential-port": 0
            }
        }
    ]
}
```

==== Setup Messaging App
. Similar to the Email App, ensure that the redirect uri specified in the Messaging App is also one of the *Valid Redirect URIs* specified in the *Keycloak Messaging Client*.
. Same as the Email App setup, you will need to initialise the Auth SDK and set the redirect uri for the Auth SDK.
. Similar to the Email app again, you will need to specify a configuration file for the app and ensure that it contains the correct configuration that was defined in <<Setup Keycloak Messaging Client>>. +

'''

Now that everything is setup, sign into the *Email App* with the user you have previously created. You should be redirected to your device browser which should have loaded the Keyclock login page.  Next, enter in your credentials and login.  You'll be asked to enter a new password for the user. You have now been authenticated on the *Email App* via your device browser.  Finally, try sign into the *Messaging App* with the same user credentials, you should be automatically logged in as you have been previously authenticated in the *Email App* via the *_same_* device browser.