== Extending metrics

User Apps and other SDK Modules can send their own metrics at any time.
To do that you need an instance of the `MetricsService` and call it's `publish` method.
This method accepts any number of objects that implement that `Metrics` interface.

=== Implementing the Metrics Interface

There are only two methods to implement:

- *identifier*: Used to categorize your data. The basic structure is this:

```
{
    "<identifier>": {
        "<metric value>": <metric data>
    },
    "<another identifier>": {
        ...
    }
}
```

- *data*: Must return a Map from String to String. This will be transformed to JSON and added under your identifier in the Metrics payload.

=== Sending Metrics data to the Backend

First retrieve an instance of the `MetricsService` from Mobile Core:

```
MetricsService metrics = core.getInstance(MetricsService.class);
```

Then use it's publish method:

```
metrics.publish(new MyMetrics());
```

where `MyMetrics` is a class implementing the `Metrics` interface. This will immediately send a request to the Metrics backend.
