= AeroGear Services Core SDK

Core SDK provides numbers of helpers for individual SDK's
Core can be also used to extract common implementations from SDK's.

Main responsibilities:

1. Configuration parser
1. Network library 
1. Default logger shared between SDK.

== Adding dependency

Add dependency to your application module
----
dependencies {
    implementation group: 'org.aerogear.android', name: 'core'
}
----

== Usage

[source,java]
----
Context context = this;
mobileCore = MobileCore.init(context);
----

For full usage see link:../../example[example] application

== Core api

Core SDK supports currently following helpers

=== Logger

Logger is initialized automatically and available as static member of AgsCore.
Example:

[source,java]
----
 AgsCore.logger.debug("Message")
----

End users can change or disable logger in top level application by providing empty implementation.

[source,java]
----
activity.mobileCore.getLogger().info("Users: " + retrievesUsers.size());
----
 
=== Network library

Network library offers common wrapper for making any networking requests.
Wrapper by default works with popular OkHttp library.

==== Usage

[source,java]
----
   HttpRequest httpRequest = activity.mobileCore.getHttpLayer().newRequest();
        httpRequest.get("https://jsonplaceholder.typicode.com/users");
        HttpResponse httpResponse = httpRequest.execute();
        httpResponse.onComplete(() -> {
            String jsonResponse = httpResponse.stringBody();
            new AppExecutors().mainThread().execute(() -> {

                List<User> retrievesUsers = new Gson()
                    .fromJson(jsonResponse, new TypeToken<List<User>>() {
                    }.getType());

                activity.mobileCore.getLogger().info("Users: " + retrievesUsers.size());

                users.addAll(retrievesUsers);
            });
        });
----
 
See link:../getting-started.adoc[SDK architecture] for more details about SDK architecture
See link:./example[example] project for examples how core can be used. 
